language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t gastus35/flutter-personal-expenses .

script:
  - docker run -e CI=true gastus35/flutter-personal-expenses flutter test